behaviors:
  Tanks:
    trainer_type: llm_trainer
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      alpha: 0.005
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
      communicator: zmq
      llm_refresh_interval: 100
      observation_types:
        - name: CameraSensor
          type: VISUAL
          index: 0
        - name: GridSensor
          type: GRID
          index: 1
          height: 30
          width: 30
          background_color: [0, 0, 0]
          tags:
            - name: Tank
              index: 0
              color: [220, 20, 60] #Â red
            - name: PowerUp
              index: 1
              color: [0, 255, 255] # light blue
            - name: Wall
              index: 2
              color: [128, 128, 128] # gray
            - name: Tank
              index: 3
              color: [148, 0, 211] # purple
        - name: RayPerceptionSensor
          type: RAYCAST
          index: 2
        - name: VectorSensor
          type: VECTORIAL
          index: 3
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      rnd:
        gamma: 0.99
        strength: 0.01
        encoding_size: 64
        learning_rate: 0.0001
    keep_checkpoints: 500
    max_steps: 50000000
    time_horizon: 2000 #1000 #64
    summary_freq: 10000
    threaded: true
    checkpoint_interval: 50000
    self_play:
      save_steps: 50000
      team_change: 200000
      swap_steps: 2000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0